inputs:
  prerelease_token:
    type: string
    description:
      "The prerelease token can be used when multiple users want to create release candidates.
      One can define an own unique token to avoid conflicts: rcN.dev, where N is a digit. For example: rc1.dev"
    required: false
    default: "rc"
  do_prerelease:
    type: boolean
    description: "If set to true, will create a prerelease. This is required to avoid creating prereleases automatically when pushing a branch."
    required: false
    default: false

pipeline:
  - step: CreateVEnv
    module: pypeline.steps.create_venv
    config:
        bootstrap_script: .bootstrap/bootstrap.py

  - step: CheckCIContext
    module: pypeline_semantic_release.steps

  - step: LintAndFormatFiles
    run: [pre-commit, run, --all-files]

  - step: ExecuteTests
    run: pytest

  - step: CreateReleaseCommit
    module: pypeline_semantic_release.steps